version: "3"

services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html/
    ports:
      - "8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: my_password
    volumes:
      - db-data:/var/lib/mysql/

volumes:
  db-data:
